spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/fleet_management?serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/mysql
spring.h2.console.enabled=false
